# Colors (Material Theme)
colors:
  # Default colors
  primary:
    background: '0x1e282d'
    foreground: '0xc4c7d1'

  # Normal colors
  normal:
    black:   '0x666666'
    red:     '0xeb606b'
    green:   '0xc3e88d'
    yellow:  '0xf7eb95'
    blue:    '0x80cbc4'
    magenta: '0xff2f90'
    cyan:    '0xaeddff'
    white:   '0xffffff'

  # Bright colors
  bright:
    black:   '0xff262b'
    red:     '0xeb606b'
    green:   '0xc3e88d'
    yellow:  '0xf7eb95'
    blue:    '0x7dc6bf'
    magenta: '0x6c71c4'
    cyan:    '0x35434d'
    white:   '0xffffff'

window:
   opacity: 1
   startup_mode: Maximized
   decorations: Full
   dynamic_padding: false
   padding:
    x: 5
    y: 5
  
font:
  normal:
    family: Hack Nerd Font
    style: Regular

  bold:
    family: Hack Nerd Font
    style: Bold

  italic:
    family: Hack Nerd Font
    style: Italic

  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic

  size: 12

mouse:
  hide_when_typing: true
  
key_bindings:
  - { key: F11,              mods: Control|Shift,                   action: ToggleFullscreen }
  - { key: N,              mods: Control|Shift,                    action: SpawnNewInstance      }
